---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "super-market"
host: "localhost:4000"
basePath: "/"
tags:
- name: "sales"
  description: "Everything about your sales"
- name: "details"
  description: "Access to purchase and sales orders"
- name: "purchase"
  description: "Everything about your purchase "
schemes:
- "http"
# - "https"
paths:
  /item_details:
    get:
      tags:
        - details
      summary: ""
      description: ""
      operationId: getItemDetails
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_details/data:
    get:
      tags:
        - details
      summary: ""
      description: ""
      operationId: getItemDetailsData
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_details/insert:
    post:
      tags:
        - details
      summary: ""
      description: ""
      operationId: getItemDetailsInsert
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters: 
        - name: items_code
          in: formData
          description: "items_code"
          required: true
          type: string
        - name: variety_name
          in: formData
          description: "variety_name"
          required: true
          type: string
        - name: items_name
          in: formData
          description: "items_name"
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_purchase:
    get:
      tags:
        - purchase
      summary: ""
      description: ""
      operationId: getItemPurchase
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_purchase/data:
    get:
      tags:
        - purchase
      summary: ""
      description: ""
      operationId: getItemPurchaseData
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object

  /item_purchase/insert:
    post:
      tags:
        - purchase
      summary: ""
      description: ""
      operationId: getItemPurchaseInsert
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters: 
        - name: variety_code
          in: formData
          description: "variety_code"
          required: true
          type: string
        - name: variety_name
          in: formData
          description: "variety_name"
          required: true
          type: string
        - name: items_name
          in: formData
          description: "items_name"
          required: true
          type: string
        - name: total_kg
          in: formData
          description: "total_kg"
          required: true
          type: string
        - name: per_kg_amt
          in: formData
          description: "per_kg_amt"
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_purchase/update_rate:
    post:
      tags:
        - purchase
      summary: ""
      description: ""
      operationId: getItemPurchaseUpdateRate
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters: 
        - name: variety_code
          in: formData
          description: "variety_code"
          required: true
          type: string
        - name: per_kg_updated_amt
          in: formData
          description: "per_kg_updated_amt"
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_purchase/update:
    post:
      tags:
        - purchase
      summary: ""
      description: ""
      operationId: getItemPurchaseUpdate
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters: 
        - name: variety_name
          in: formData
          description: "variety_name"
          required: true
          type: string
        - name: total_kg
          in: formData
          description: "total_kg"
          required: true
          type: string
        - name: total_kg_amt
          in: formData
          description: "total_kg_amt"
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_sales:
    get:
      tags:
        - sales
      summary: ""
      description: ""
      operationId: getItemSales
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_sales/data:
    get:
      tags:
        - sales
      summary: ""
      description: ""
      operationId: getItemSalesData
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
  /item_sales/insert:
    post:
      tags:
        - sales
      summary: ""
      description: ""
      operationId: getItemSalesInsert
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: items_code
          in: formData
          description: "items_code"
          required: true
          type: string
        - name: variety_code
          in: formData
          description: "variety_code"
          required: true
          type: string
        - name: items_name
          in: formData
          description: "items_name"
          required: true
          type: string
        - name: variety_name
          in: formData
          description: "variety_name"
          required: true
          type: string
        - name: items_kg
          in: formData
          description: "items_kg"
          required: true
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            type: object
# https://github.com/swagger-api/swagger-ui/issues/5778
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject